USE Chinook;
-- ===================================================
-- task04: SQL INTERMEDIATES   - JOINS
-- DATABASE - chinook
-- OBJECTIVE: Demonstrate INNER JOIN, LEFT JOIN, and revenue analysis using joint tables 
-- ====================================================

-- ===================================================
-- INNER JOIN: Combines customer detail with the order detail(invoices)
-- OBJECTIVE: to view which customer have placed order
-- ===================================================

    
select
c.CustomerId, 
c.FirstName,
c.LastName,
i.InvoiceId,
i.Total
from customer c
inner join Invoice i
on c.CustomerId = i.CustomerId;


-- ============================================
-- 2. LEFT JOIN: To find customer who never placed any order 
--  OBJECTIVE: identify inactive customer for bussiness insight
-- ============================================

  
select 
c.CustomerId,
c.FirstName,
c.LastName
from customer c
left join Invoice i
on c.CustomerId = i.CustomerId
where i.InvoiceId is null;

-- ============================================
-- 3. REVENUE PER PRODUCT
-- join invoices line items with track details
-- purpose: calculate total revenue generated by each product
-- ============================================   


select 
t.Name as Track_name,
sum(il.unitprice* il.Quantity) as revenue
from Invoiceline il
inner join Track t
ON il.TrackId = t.TrackId
GROUP BY t.Name
ORDER BY revenue DESC;